### ISSUE TITLE
cassandra is unavailable - sleeping

### ISSUE THREAD

**Issue by msitdevops** [msitdevops/spring-microservice#4]
cassandra is failing to start when running the docker-compose file

**Comment by sgowtham36** [comment]
First of all, Be sure! Your local cassandra should not work. Because docker will use same port for cassandra.

Secondly, you can test only Cassandra image. Pull cassandra from docker. Then create container. Then test your cassandra with examle queries like "Create new keyspace..."

There are some differences on docker-compose. You can check it.
https://github.com/senolatac/course-enrollment/blob/master/docker-compose.yml
